cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: myaccesskey
      secret-key: mysecretkey
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/mysqsname